### PR TITLE
append headers if set

### PR DESCRIPTION
**Pull request by jsergio123**

### CODE REVIEW

**Comment by jsergio123** [comment]
It should be compatible with existing addons.

**Comment by jsergio123** [comment]
All its doing is updating the existing headers dictionary. Useful for just appending for example a referer.

**Comment by romanvm** [comment]
Mutable default argument (an empty dict `{}` in this case) is absolute no go in Python world. Also you shouldn't manipulate mutable globals inside your code (whether mutable globals should be used at all is another matter). Use shallow or deep copy to obtain your own instance of headers and do whatever you want with them.

**Comment by jsergio123** [comment]
@learningit Please provide example of who this would break an existing addon? I have already run multiple scenarios and all worked fine.

@romanvm why when I can simply pass headers = ("Referer" : referer} and have the referer added to the default httpHeaders?

**Comment by learningit** [comment]
You really love to argue things that you don't understand. 

_headers = httpHeaders references the same object. When you modify _headers, you modify httpHeaders, which means all subsequent call have the fields that you added.

You assume that call add-ons will call using defaultHeaders. I originally wrote the method to accept a totally new set of headers because there are a number of add-ons which cannot use defaultHeaders on some calls. Your code always use defaultHeaders and simply appends.

You also don't seem to understand what @romanvm has explained to you.

How many more examples of wrong do you need?

**Comment by jsergio123** [comment]
No I do understand. I'm not arguing. You guys just like to put others down with your snobbish attitudes. Meanwhile you scrutinize 2 lines of code to a poorly written script that lack basic functionality like something so simply.

**Comment by peak3d** [comment]
@jsergio123 assume there is an addon which don't want to use the default headers (and there will be most likely some out in the world). This is not possible after your change, because default headers are added always.

One can discuss that the last occurence wins, but this is risky for addon devs wich may dont want to have gziped option only.

As long we don't know what addons are using this library, existing functionality must not be changed.
I hope you understand (or I don't understand the code change)

**Comment by jsergio123** [comment]
Dict.update() will update any existing key with the new value passed. In essence replacing the default header. How about we use something like repl.it to show working examples instead of just going back and forth. I'm at work now but I can show working examples when I get home.

**Comment by learningit** [comment]
How about no. You don't seem to understand that I am the author t1m and have more than 60 add-ons using this library. I think I understand how and why the library works.

**Comment by jsergio123** [comment]
Why you guys such little crying pussies? Why don't you guys try making some half decent addons for Kodi instead of basically the text browsers addons you guys have in the org repo. 90% of your user base goes elsewhere even for non piracy addons. You guys create scripts meant to make it easier for novice developers to Kodi make addons but you don't ever update them. You just leave broke and when some tries to fix or add functionality you tell them to get lost. Fuck you @learningit now don't go stealing anymore of my addons.

**Comment by jsergio123** [comment]
Here come pussy ass lunatixz to the rescue. You still a little scared bitch right? When we going to meet so I can smack the bullshit out of you?

Yup I'm the best copy and paste dev around lol. Why you guys act like little entitled pussies? You don't teach anyone anything to learn. You just dismiss people like your too good for me or something. Then you close my pr's like hah you can't join out circle jerk.

**Comment by jsergio123** [comment]
Lol my "over inflated ego". I'm the most humble dev out here. I help everyone and work with everyone. I give respect and credit where do. Everyone knows it. @lunatixz are you a female because you sure do act like one.

**Comment by Lunatixz** [comment]
I guess you are a humble sexist.... kudos

**Pull request closed without merging**
